name: PalCraftEssentials
main: me.davejavu.pce.PalCraftEssentials
version: 2.0
description: PCE
authors: [davejavu]
permissions:
    PalCraftEssentials.*:
        default: op
        children:
            PalCraftEssentials.alt.view: true
            PalCraftEssentials.chat.colours: true
            PalCraftEssentials.command.allplayers: true
            PalCraftEssentials.command.back: true
            PalCraftEssentials.command.ban: true
            PalCraftEssentials.command.banip: true
            PalCraftEssentials.command.blockplayer: true
            PalCraftEssentials.command.blockcmd: true
            PalCraftEssentials.command.bsearch: true
            PalCraftEssentials.command.bupdate: true
            PalCraftEssentials.command.censor: true
            PalCraftEssentials.command.clearinventory: true
            PalCraftEssentials.command.convert: true
            PalCraftEssentials.command.enchant: true
            PalCraftEssentials.command.fly: true
            PalCraftEssentials.command.force: true
            PalCraftEssentials.command.freeze: true
            PalCraftEssentials.command.gamemode: true
            PalCraftEssentials.command.give: true
            PalCraftEssentials.command.god: true
            PalCraftEssentials.command.god.others: true
            PalCraftEssentials.command.heal: true
            PalCraftEssentials.command.heal.others: true
            PalCraftEssentials.command.home: true
            PalCraftEssentials.command.home.others: true
            PalCraftEssentials.command.item: true
            PalCraftEssentials.command.kick: true
            PalCraftEssentials.command.kickall: true
            PalCraftEssentials.command.more: true
            PalCraftEssentials.command.setmotd: true
            PalCraftEssentials.command.msg: true
            PalCraftEssentials.command.msg.colours: true
            PalCraftEssentials.command.mute: true
            PalCraftEssentials.command.pce: true
            PalCraftEssentials.command.playtime.self: true
            PalCraftEssentials.command.playtime.others: true
            PalCraftEssentials.command.repair: true
            PalCraftEssentials.command.serverinfo: true
            PalCraftEssentials.command.sethome: true
            PalCraftEssentials.command.setspawn: true
            PalCraftEssentials.command.setwarp: true
            PalCraftEssentials.command.silent: true
            PalCraftEssentials.command.socialspy: true
            PalCraftEssentials.command.speed: true
            PalCraftEssentials.command.stalk: true
            PalCraftEssentials.command.superpick: true
            PalCraftEssentials.command.superpick.bedrock: true
            PalCraftEssentials.command.tempban: true
            PalCraftEssentials.command.time: true
            PalCraftEssentials.command.tp: true
            PalCraftEssentials.command.tpa: true
            PalCraftEssentials.command.tpaccept: true
            PalCraftEssentials.command.tpahere: true
            PalCraftEssentials.command.tpdeny: true
            PalCraftEssentials.command.tphere: true
            PalCraftEssentials.command.tptoggle: true
            PalCraftEssentials.command.tpo: true
            PalCraftEssentials.command.tpohere: true
            PalCraftEssentials.command.tptoggle: true
            PalCraftEssentials.command.troll: true
            PalCraftEssentials.command.unban: true
            PalCraftEssentials.command.vanish: true
            PalCraftEssentials.command.vanish.see: true
            PalCraftEssentials.command.warn: true
            PalCraftEssentials.command.warp: true
            PalCraftEssentials.command.warp.list: true
            PalCraftEssentials.command.warp.others: true
            PalCraftEssentials.command.weather: true
            PalCraftEssentials.command.whois: true
            PalCraftEssentials.geoip.view: true
            PalCraftEssentials.exempt.ban: true
            PalCraftEssentials.exempt.kick: true
            PalCraftEssentials.launchfireball: true
            PalCraftEssentials.sign.warp.create: true
            PalCraftEssentials.sign.warp.use: true
            PalCraftEssentials.sign.warp.remove: true
    
commands:
  allplayers:
    description: All player stuff
  back:
    description: Teleport back
  ban:
    description: Ban, also whobanned/banreason/prevbans
  banip:
    description: Ban an IP
  blockplayer:
    description: blockplayer a player.
  blockcmd:
    description: blockplayer a players commands
  bsearch:
    description: Search the bans
  bupdate:
    description: Update a ban
  censor:
    description: Toggle censoring a players' messages
  clearinventory:
    description: Clear inventory
    aliases: [ci,clearinv]
  chat:
    description: Chat
  convert:
    description: Convert bans from/to MySQL
  delwarp:
    description: Delete a warp
  enchant:
    description: Enchant the item in your hand
  felloutworld:
    description: Retrieve inventory if fallen out world.
  fly:
    description: Fly
  force:
    description: Force a player to do a command
  freeze:
    description: Freeze a player
  fuckthehaters:
    description: for dave.
  gamemode:
    description: Switch gamemode
    aliases: [gm,game,mode]
  give:
    description: Give an item
    aliases: [g]
  givesethacookie:
    description: Lol.
  god:
    description: Toggle god mode
  heal:
    description: Heal yourself or another player
  home:
    description: Teleport to your home
  item:
    description: Give yourself an item
    aliases: [i]
  kick:
    description: Kick a player
  kickall:
    description: Kick all players online
  list:
    description: List all players online
  me:
    description: /me!
  more:
    description: Give more of the item in hand
  setmotd:
    description: Change the server motd
  msg:
    description: Message another player
    aliases: [tell,message,m,tell,t,pmsg]
  mute:
    description: Mute a player
  pce:
    description: PCE!
    aliases: [palcraftessentials]
  playtime:
    description: See playtime.
  pvp:
    description: Toggle PVP
  repair:
    description: Repair the item in hand
  reply:
    description: Reply to the previous message
    aliases: [r,preply]
  serverinfo:
    description: Info about server
    aliases: [sinfo,si,serveri,pserverinfo]
  sethome:
    description: Set home
  setspawn:
    description: Set spawn
  setwarp:
    description: Set a warp
    aliases: [sw]
  socialspy:
    description: Socialspy.
  spawn:
    description: Teleport to spawn
  spawnwither:
    description: Spawn wither
  speed:
    description: Change your running speed
  stalk:
    description: Scroll through online players
  superpick:
    description: Super pickaxe.
    aliases: [/,psp]
  tempban:
    description: Tempban
  tp:
    description: Teleport
  tpa:
    description: Ask to teleport to a player
    aliases: [tpask]
  tpaccept:
    description: Accept the /tpa
  tpahere:
    description: Ask a player to teleport to you
  tpdeny:
    description: Deny the /tpa
  tphere:
    description: Teleport a player to you
  tptoggle:
    description: Toggle teleportation
  tpo:
    description: Override /tptoggle
    aliases: [tpoverride]
  tpohere:
    description: Override /tptoggle
  troll:
    description: lol
  unban:
    description: Unban a player/ip/temp ban
  vanish:
    description: Vanish
    aliases: [v]
  warn:
    description: Warn a player, list/add/remove also.
  warp:
    description: Teleport to a warp
    aliases: [w]
  weather:
    description: Change the weather in game
  whois:
    description: See info about a player
  